server:
  type: python:3.11
  disk: 256

  hooks:
    build: |
      pip install -r requirements.txt

  web:
    commands:
      start: uvicorn app.main:app


  source:
    root: "server"

client:
  type: nodejs:18
  dist: 256

  hooks:
    build: |
      npm install 
      npm run build

  web:
    locations:
      "/":
        root: "build"
        passthru: '/index.html'
